"""add colum is_dttm for RestColum

Revision ID: 54714cda3489
Revises: c84b70a0e697
Create Date: 2016-10-07 15:32:25.813806

"""

# revision identifiers, used by Alembic.
revision = '54714cda3489'
down_revision = 'c84b70a0e697'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest_colums', sa.Column('is_dttm', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest_colums', 'is_dttm')
    ### end Alembic commands ###
