"""add rest colum/metric

Revision ID: aaeb9fea445f
Revises: e62c6ea46193
Create Date: 2016-10-06 15:21:27.446422

"""

# revision identifiers, used by Alembic.
revision = 'aaeb9fea445f'
down_revision = 'e62c6ea46193'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_colums',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('groupby', sa.Boolean(), nullable=True),
    sa.Column('count_distinct', sa.Boolean(), nullable=True),
    sa.Column('sum', sa.Boolean(), nullable=True),
    sa.Column('max', sa.Boolean(), nullable=True),
    sa.Column('min', sa.Boolean(), nullable=True),
    sa.Column('filterable', sa.Boolean(), nullable=True),
    sa.Column('desciption', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['rest_datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rest_metrics',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=512), nullable=True),
    sa.Column('verbose_name', sa.String(length=1024), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('d3format', sa.String(length=128), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['rest_datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rest_datasources', sa.Column('server_url', sa.String(length=250), nullable=True))
    op.drop_constraint(u'rest_datasources_ibfk_3', 'rest_datasources', type_='foreignkey')
    op.create_foreign_key(None, 'rest_datasources', 'rest_server', ['server_url'], ['server_url'])
    op.drop_column('rest_datasources', 'server_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest_datasources', sa.Column('server_name', sa.String(length=250), nullable=True))
    op.drop_constraint(u'rest_datasources_ibfk_5', 'rest_datasources', type_='foreignkey')
    op.create_foreign_key(None, 'rest_datasources', 'rest_server', ['server_name'], ['server_name'])
    op.drop_column('rest_datasources', 'server_url')

    op.drop_table('rest_metrics')
    op.drop_table('rest_colums')
    ### end Alembic commands ###

