"""add colum cache_timeout to RestServerModel

Revision ID: c84b70a0e697
Revises: aaeb9fea445f
Create Date: 2016-10-07 14:27:32.009778

"""

# revision identifiers, used by Alembic.
revision = 'c84b70a0e697'
down_revision = 'aaeb9fea445f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest_server', sa.Column('cache_timeout', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest_server', 'cache_timeout')
    ### end Alembic commands ###
